version: '3'

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017'

  capsuladotempo:
    image: capsuladotempo
    build:
      context: .
      dockerfile: CapsulaDoTempo/Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    environment:
     - ConnectionStrings:MongoDB = "mongodb://mongo:27017"

  capsuladotempoui:
    image: capsuladotempoui
    build:
      context: .
      dockerfile: CapsulaDoTempoUI/Dockerfile
    depends_on:
      - capsuladotempo
    links:
      - capsuladotempo

