version: '3'

services:
  capsuladotempo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  capsuladotempoui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

